FLASHECU	for programing the FLASH memory of a SAAB Trionic ECU
1: Error: Could not read from BIN file
2: Error: Could not open BIN file
3: Error: Unrecognised ECU or FLASH chips
4: Unable to program FLASH chips
5: Unable to erase FLASH chips
